sudo: required
branches:
    only:
        - master
language: go
services:
    - docker
before_install:
  - sudo apt-get install -y git
install:
  - make get-deps
script:
  - make build
  - make unit
